wandb_version: 1

activation:
  value: mish
batch_norm:
  value: true
data_aug:
  value: true
dense_neurons:
  value: 128
dropout:
  value: 0.3
filter_config:
  value:
  - 32
  - 64
  - 64
  - 128
  - 128
kernel_size:
  value: 3
lr:
  value: 0.0005
