wandb_version: 1

activation:
  value: mish
batch_norm:
  value: false
data_aug:
  value: false
dense_neurons:
  value: 128
dropout:
  value: 0.3
filter_config:
  value:
  - 32
  - 32
  - 32
  - 32
  - 32
kernel_size:
  value: 3
lr:
  value: 0.0005
