wandb_version: 1

activation:
  value: Mish
batch_norm:
  value: true
batch_size:
  value: 64
data_augmentation:
  value: false
dropout:
  value: '0.2'
epochs:
  value: 5
filter_organization:
  value: double
filter_size:
  value: 5
learning_rate:
  value: 0.0021721285025155896
num_filters:
  value: 16
optimizer:
  value: SGD
weight_decay:
  value: 0.006820787209348182
weight_init:
  value: xavier
