_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation:
    value: relu
batch_norm:
    value: false
data_aug:
    value: true
dense_neurons:
    value: 64
dropout:
    value: 0.2
filter_config:
    value:
        - 32
        - 64
        - 64
        - 128
        - 128
kernel_size:
    value: 3
lr:
    value: 0.01
